FROM alpine:latest

RUN apk --no-cache add openssl git make clang g++

RUN git clone https://github.com/ggerganov/llama.cpp.git /usr/llama.cpp

WORKDIR /usr/llama.cpp

RUN make

WORKDIR /usr/workspace/backend
